# Generated by Django 2.0.2 on 2018-02-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='date',
            field=models.DateTimeField(blank=True, default='2018-02-23 18:29:27', null=True),
        ),
    ]
