# Generated by Django 2.0.2 on 2018-02-23 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180223_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 2, 23, 18, 34, 5, 318837), null=True),
        ),
    ]
