# Generated by Django 2.0.2 on 2018-02-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180223_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
